[package]
name = "Studio"
version = "1.0.0"
authors = ["lay (Aladeen)"]

[addresses]
townespace = "0x8ccfe7bf29ea35b26c2d42b1ff05acfbd6283ba5970bdb1ffca8110224adc5de"

[dev-addresses]

[dependencies.ComposableToken]
local = "./ComposableToken"

[dependencies.TokenMinter]
local = "./TokenMinter"
