[package]
name = "Studio"
version = "1.0.0"
authors = ["lay (Aladeen)"]

[addresses]
townespace = "0xb33f54fabd7f384d03feb0a6ce4f96545e90c94ce74f6e2b490906f485fd4b71"

[dev-addresses]

[dependencies.ComposableToken]
local = "./ComposableToken"

[dependencies.TokenMinter]
local = "./TokenMinter"
