[package]
name = "Studio"
version = "1.0.0"
authors = ["lay (Aladeen)"]

[addresses]
townespace = "0xd85adb3c424c398d5017ad1d20b63ce8b3373a651a484ff2b473aa93d3357296"

[dev-addresses]

[dependencies.ComposableToken]
local = "./ComposableToken"

[dependencies.TokenMinter]
local = "./TokenMinter"
