[package]
name = "Studio"
version = "1.0.0"
authors = ["lay (Aladeen)"]

[addresses]
# TODO: Publish with the modules visibility hidden
townespace = "0x5094651b0c628ceea4d38ce64e08965f15f5c1c010fe33d1b2ec991638251374"

[dev-addresses]

[dependencies.ComposableToken]
local = "./ComposableToken"

[dependencies.TokenMinter]
local = "./TokenMinter"
