[package]
name = "Studio"
version = "1.0.0"
authors = ["lay (Aladeen)"]

[addresses]
townespace = "0xe493837288549ff55e80c52556356e025e83879791cddc434976d7c8a0dcc4ae"

[dev-addresses]

[dependencies.ComposableToken]
local = "./ComposableToken"

[dependencies.TokenMinter]
local = "./TokenMinter"
