[package]
name = "Examples"
version = "1.0.0"
authors = []

[addresses]
examples = "effb9356ede780467b845c6ae6ec90592b5293f44392ddb39b1776ba72f64a83"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Studio-alpha]
git = "https://github.com/TowneSquare/TowneSpace-contract"
rev = "v0.2.0-alpha"
subdir = ""

[dev-dependencies]
