[package]
name = "Examples"
version = "1.0.0"
authors = ["lay (Aladeen)"]

[addresses]
townespace = "0x0c408b87f4adcbca12d2e8b9cd0a62a0886746bad66aa29eea4cbcd0fe66958a"
examples = "effb9356ede780467b845c6ae6ec90592b5293f44392ddb39b1776ba72f64a83"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Composables]
git = "https://github.com/TowneSquare/TowneSpace-contract"
rev = "v0.2.0-alpha"
subdir = ""

[dev-dependencies]
